"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { TransactionInput, XAIFactor } from "./types";
import { MLInferenceResult } from "./riskEngine";

export type CaseStatus = "NEW" | "UNDER REVIEW" | "ESCALATED" | "RESOLVED";
export type CaseDisposition = "NO_ACTION" | "FALSE_POSITIVE" | "ESCALATED_L2" | "CONFIRMED_SUSPICIOUS" | "";

export interface AuditEvent {
  id: string;
  timestamp: string;
  action: string;
  actor: string;
}

export interface AnalystNote {
  id: string;
  text: string;
  author: string;
  timestamp: string;
}

export interface RiskCase {
  caseId: string;
  transaction: TransactionInput;
  riskAssessment: MLInferenceResult;
  status: CaseStatus;
  assignedTo: string;
  notes: AnalystNote[];
  disposition: CaseDisposition;
  createdAt: string;
  updatedAt: string;
  auditEvents: AuditEvent[];
  scenarioLabel?: string;
}

interface CasesContextType {
  cases: RiskCase[];
  addCase: (newCase: RiskCase) => void;
  updateCase: (caseId: string, updates: Partial<RiskCase>) => void;
  addNote: (caseId: string, noteText: string, author: string) => void;
  addAuditEvent: (caseId: string, action: string, actor: string) => void;
  resetToDefaults: () => void;
}

const CasesContext = createContext<CasesContextType | undefined>(undefined);

const SEED_CASES: RiskCase[] = [
  {
    caseId: "CASE-2026-0891",
    scenarioLabel: "Mule Ring Funneling",
    transaction: {
      id: "TXN-882194",
      timestamp: new Date(Date.now() - 14 * 60000).toISOString(),
      senderAccount: "AC••••4912",
      receiverAccount: "AC••••9901",
      amount: 48500,
      type: "SEND_MONEY",
      hourOfDay: 2,
      isNewDevice: true,
      isUnusualLocation: true,
      accountAgeDays: 14,
      receiverIsNew: true,
      transactionVelocity: 22,
    },
    riskAssessment: {
      fraudProbability: 94.2,
      anomalyScore: 89.5,
      networkRiskScore: 92.0,
      finalRiskScore: 92.8,
      riskLevel: "CRITICAL",
      recommendedAction: "BLOCK_AND_ESCALATE",
      modelVersion: { fraud: "xgb-v1", anomaly: "iforest-v1", network: "graph-v1" },
      xaiFactors: [
        { label: "Abnormal Velocity (22 tx/hr)", weight: 34.5, category: "Behavioral", direction: "POSITIVE", explanation: "Exceeds 99.8th percentile for peer accounts" },
        { label: "Account Age (14 Days)", weight: 26.2, category: "Profile", direction: "POSITIVE", explanation: "Young account executing max daily tier limits" },
        { label: "Nocturnal Hour (02:00 AM)", weight: 19.8, category: "Context", direction: "POSITIVE", explanation: "High concentration of automated cash extractions" },
        { label: "Unrecognized Device Fingerprint", weight: 12.3, category: "Device", direction: "POSITIVE", explanation: "First login from unknown Android IMEI" }
      ]
    },
    status: "ESCALATED",
    assignedTo: "Fraud Operations L2",
    disposition: "CONFIRMED_SUSPICIOUS",
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    notes: [
      { id: "n1", text: "Recipient AC••••9901 flagged in central mule repository. BFIU reporting triggered.", author: "Analyst Nahid", timestamp: new Date(Date.now() - 18 * 60000).toISOString() }
    ],
    auditEvents: [
      { id: "e1", timestamp: new Date(Date.now() - 25 * 60000).toISOString(), action: "Case auto-generated by Fusion Engine", actor: "AI System" },
      { id: "e2", timestamp: new Date(Date.now() - 18 * 60000).toISOString(), action: "Escalated to L2 Fraud Bureau", actor: "Analyst Nahid" }
    ]
  },
  {
    caseId: "CASE-2026-0888",
    scenarioLabel: "Midnight SIM-Swap ATO",
    transaction: {
      id: "TXN-881940",
      timestamp: new Date(Date.now() - 48 * 60000).toISOString(),
      senderAccount: "AC••••3142",
      receiverAccount: "AC••••7211",
      amount: 25000,
      type: "CASH_OUT",
      hourOfDay: 3,
      isNewDevice: true,
      isUnusualLocation: true,
      accountAgeDays: 45,
      receiverIsNew: true,
      transactionVelocity: 14,
    },
    riskAssessment: {
      fraudProbability: 88.4,
      anomalyScore: 82.1,
      networkRiskScore: 78.0,
      finalRiskScore: 85.6,
      riskLevel: "CRITICAL",
      recommendedAction: "BLOCK_AND_ESCALATE",
      modelVersion: { fraud: "xgb-v1", anomaly: "iforest-v1", network: "graph-v1" },
      xaiFactors: [
        { label: "SIM & Device Age Discrepancy", weight: 31.0, category: "Device", direction: "POSITIVE", explanation: "IMEI switch registered 20 minutes before withdrawal" },
        { label: "Off-Hour Cash-out (03:00 AM)", weight: 28.4, category: "Temporal", direction: "POSITIVE", explanation: "Targeting dormant agent float balance" },
        { label: "Rapid Balance Drain (৳25k)", weight: 22.0, category: "Monetary", direction: "POSITIVE", explanation: "98% of available balance depleted in one hit" }
      ]
    },
    status: "UNDER REVIEW",
    assignedTo: "Senior Reviewer Farhan",
    disposition: "",
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    notes: [
      { id: "n2", text: "SMS verification was requested from Gazipur tower; customer registered in Sylhet.", author: "Farhan R.", timestamp: new Date(Date.now() - 22 * 60000).toISOString() }
    ],
    auditEvents: [
      { id: "e3", timestamp: new Date(Date.now() - 45 * 60000).toISOString(), action: "Case auto-generated by Fusion Engine", actor: "AI System" },
      { id: "e4", timestamp: new Date(Date.now() - 30 * 60000).toISOString(), action: "Assigned to Senior Reviewer Farhan", actor: "Supervisor" }
    ]
  },
  {
    caseId: "CASE-2026-0879",
    scenarioLabel: "Wrong Number Refund Scam",
    transaction: {
      id: "TXN-876102",
      timestamp: new Date(Date.now() - 110 * 60000).toISOString(),
      senderAccount: "AC••••7721",
      receiverAccount: "AC••••1183",
      amount: 18500,
      type: "SEND_MONEY",
      hourOfDay: 15,
      isNewDevice: false,
      isUnusualLocation: false,
      accountAgeDays: 320,
      receiverIsNew: true,
      transactionVelocity: 6,
    },
    riskAssessment: {
      fraudProbability: 61.2,
      anomalyScore: 54.0,
      networkRiskScore: 45.0,
      finalRiskScore: 56.4,
      riskLevel: "MODERATE",
      recommendedAction: "CHALLENGE_OTP_BIOMETRIC",
      modelVersion: { fraud: "xgb-v1", anomaly: "iforest-v1", network: "graph-v1" },
      xaiFactors: [
        { label: "New Recipient Transfer", weight: 27.5, category: "Network", direction: "POSITIVE", explanation: "Unseen recipient with zero previous handshake" },
        { label: "Sudden Amount Spike", weight: 19.3, category: "Monetary", direction: "POSITIVE", explanation: "3.5x higher than 30-day average transaction" }
      ]
    },
    status: "NEW",
    assignedTo: "Risk Analyst 01",
    disposition: "",
    createdAt: new Date(Date.now() - 105 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 105 * 60000).toISOString(),
    notes: [],
    auditEvents: [
      { id: "e5", timestamp: new Date(Date.now() - 105 * 60000).toISOString(), action: "Step-Up Biometric Challenge triggered", actor: "AI Engine" }
    ]
  },
  {
    caseId: "CASE-2026-0865",
    scenarioLabel: "Agent Liquidity Stress",
    transaction: {
      id: "TXN-869910",
      timestamp: new Date(Date.now() - 180 * 60000).toISOString(),
      senderAccount: "AC••••8830",
      receiverAccount: "AC••••4421",
      amount: 35000,
      type: "CASH_OUT",
      hourOfDay: 18,
      isNewDevice: false,
      isUnusualLocation: true,
      accountAgeDays: 610,
      receiverIsNew: true,
      transactionVelocity: 8,
    },
    riskAssessment: {
      fraudProbability: 48.0,
      anomalyScore: 42.0,
      networkRiskScore: 35.0,
      finalRiskScore: 44.5,
      riskLevel: "MODERATE",
      recommendedAction: "CHALLENGE_OTP_BIOMETRIC",
      modelVersion: { fraud: "xgb-v1", anomaly: "iforest-v1", network: "graph-v1" },
      xaiFactors: [
        { label: "Unusual Geolocation Area", weight: 22.0, category: "Location", direction: "POSITIVE", explanation: "Cashout requested 45km away from customer primary district" }
      ]
    },
    status: "RESOLVED",
    assignedTo: "Analyst Nahid",
    disposition: "FALSE_POSITIVE",
    createdAt: new Date(Date.now() - 175 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60000).toISOString(),
    notes: [
      { id: "n3", text: "Customer verified via live video KYC. Legitimate business trip withdrawal.", author: "Analyst Nahid", timestamp: new Date(Date.now() - 65 * 60000).toISOString() }
    ],
    auditEvents: [
      { id: "e6", timestamp: new Date(Date.now() - 175 * 60000).toISOString(), action: "Flagged by Anomaly Model", actor: "AI System" },
      { id: "e7", timestamp: new Date(Date.now() - 60 * 60000).toISOString(), action: "Resolved as False Positive", actor: "Analyst Nahid" }
    ]
  },
  {
    caseId: "CASE-2026-0852",
    scenarioLabel: "Merchant Grocery QR",
    transaction: {
      id: "TXN-864112",
      timestamp: new Date(Date.now() - 240 * 60000).toISOString(),
      senderAccount: "AC••••1234",
      receiverAccount: "AC••••9988",
      amount: 1450,
      type: "MERCHANT_PAY",
      hourOfDay: 13,
      isNewDevice: false,
      isUnusualLocation: false,
      accountAgeDays: 850,
      receiverIsNew: false,
      transactionVelocity: 1,
    },
    riskAssessment: {
      fraudProbability: 4.1,
      anomalyScore: 5.2,
      networkRiskScore: 2.0,
      finalRiskScore: 3.8,
      riskLevel: "LOW",
      recommendedAction: "AUTO_APPROVE",
      modelVersion: { fraud: "xgb-v1", anomaly: "iforest-v1", network: "graph-v1" },
      xaiFactors: [
        { label: "Frequent Merchant Partner", weight: 14.5, category: "Trust", direction: "NEGATIVE", explanation: "Established 2-year verified transaction history" },
        { label: "Normal Working Hours", weight: 9.8, category: "Context", direction: "NEGATIVE", explanation: "Standard shopping activity pattern" }
      ]
    },
    status: "RESOLVED",
    assignedTo: "Automated System",
    disposition: "NO_ACTION",
    createdAt: new Date(Date.now() - 240 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 240 * 60000).toISOString(),
    notes: [],
    auditEvents: [
      { id: "e8", timestamp: new Date(Date.now() - 240 * 60000).toISOString(), action: "Auto-approved within 18ms", actor: "AI System" }
    ]
  }
];

export function CasesProvider({ children }: { children: ReactNode }) {
  const [cases, setCases] = useState<RiskCase[]>([]);
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    try {
      const stored = localStorage.getItem("upay_shield_cases_v2");
      if (stored) {
        setCases(JSON.parse(stored));
      } else {
        setCases(SEED_CASES);
      }
    } catch {
      setCases(SEED_CASES);
    }
    setIsLoaded(true);
  }, []);

  useEffect(() => {
    if (isLoaded) {
      try {
        localStorage.setItem("upay_shield_cases_v2", JSON.stringify(cases));
      } catch (e) {
        console.error("Storage error:", e);
      }
    }
  }, [cases, isLoaded]);

  const addCase = (newCase: RiskCase) => {
    setCases(prev => [newCase, ...prev]);
  };

  const updateCase = (caseId: string, updates: Partial<RiskCase>) => {
    setCases(prev => prev.map(c => c.caseId === caseId ? { ...c, ...updates, updatedAt: new Date().toISOString() } : c));
  };

  const addNote = (caseId: string, noteText: string, author: string) => {
    setCases(prev => prev.map(c => {
      if (c.caseId === caseId) {
        return {
          ...c,
          notes: [...c.notes, { id: "n-" + Date.now(), text: noteText, author, timestamp: new Date().toISOString() }],
          updatedAt: new Date().toISOString()
        };
      }
      return c;
    }));
  };

  const addAuditEvent = (caseId: string, action: string, actor: string) => {
    setCases(prev => prev.map(c => {
      if (c.caseId === caseId) {
        return {
          ...c,
          auditEvents: [...c.auditEvents, { id: "e-" + Date.now(), action, actor, timestamp: new Date().toISOString() }]
        };
      }
      return c;
    }));
  };

  const resetToDefaults = () => {
    setCases(SEED_CASES);
    try {
      localStorage.setItem("upay_shield_cases_v2", JSON.stringify(SEED_CASES));
    } catch {}
  };

  return (
    <CasesContext.Provider value={{ cases, addCase, updateCase, addNote, addAuditEvent, resetToDefaults }}>
      {children}
    </CasesContext.Provider>
  );
}

export function useCases() {
  const context = useContext(CasesContext);
  if (context === undefined) {
    throw new Error("useCases must be used within a CasesProvider");
  }
  return context;
}
